/** Demo slice of a much larger in-game catalog. Only chase cards can be filed. */
export const CATALOG = [
  {
    id: 1,
    slug: "legally-mime",
    name: "Legally Mime",
    rarity: "legendary",
    faction: "Legal",
    type: "Character",
    chase: true,
    copies: 1,
    image: "/courthouse/legally-mime.jpg",
    text: "The clerk who never speaks. Filing this card stamps a real title.",
  },
  {
    id: 2,
    slug: "the-courtroom",
    name: "The Courtroom",
    rarity: "rare",
    faction: "Legal",
    type: "Stage",
    chase: true,
    copies: 1,
    image: "/courthouse/courtroom.jpg",
    text: "Stage: Federal Court. Hostile tactics cost extra budget here.",
  },
  {
    id: 3,
    slug: "golden-scale",
    name: "Golden Scale",
    rarity: "legendary",
    faction: "Legal",
    type: "Artifact",
    chase: true,
    copies: 1,
    image: "/courthouse/golden-scale.jpg",
    text: "Artifact. At end of turn, restore 1 HQ if you control a Legal unit.",
  },
  {
    id: 4,
    slug: "piece-treaty",
    name: "Piece Treaty",
    rarity: "legendary",
    faction: "Wild card",
    type: "Artifact",
    chase: true,
    copies: 1,
    image: "/courthouse/piece-treaty.jpg",
    text: "The stamp itself. Filed copies become tradable title deeds.",
  },
  {
    id: 5,
    slug: "silent-brief",
    name: "Silent Brief",
    rarity: "rare",
    faction: "Legal",
    type: "Tactic",
    chase: true,
    copies: 2,
    image: "/courthouse/silent-brief.jpg",
    text: "Instant: cancel a pending hostile tactic unless the Stage is already Court.",
  },
  {
    id: 6,
    slug: "night-clerk",
    name: "Night Clerk",
    rarity: "rare",
    faction: "Legal",
    type: "Character",
    chase: true,
    copies: 1,
    image: "/courthouse/night-clerk.jpg",
    text: "On arrival: privately inspect the opponent’s oldest hand card.",
  },
  {
    id: 7,
    slug: "red-balloon",
    name: "Red Balloon",
    rarity: "common",
    faction: "Wild card",
    type: "Tactic",
    chase: false,
    copies: 4,
    image: "/courthouse/red-balloon.jpg",
    text: "Starter copy. Plays fine in a 20-card deck. Cannot be filed.",
  },
];

export const CATALOG_SIZE_HINT = 600;
