/** Slice of the live catalog. Numbers match in-game card numbers / art slots. */
export const CATALOG = [
  {
    id: 200,
    slug: "legally-mime",
    name: "Legally Mime",
    rarity: "rare",
    faction: "Wild card",
    type: "Character",
    chase: true,
    copies: 1,
    text: "His counsel is to remain silent.",
  },
  {
    id: 31,
    slug: "bjc",
    name: "BJC",
    rarity: "rare",
    faction: "Wild card",
    type: "Character",
    chase: true,
    copies: 1,
    text: "The stream has notes. Several tabs of notes.",
  },
  {
    id: 1,
    slug: "ammon-razor",
    name: "Ammon’s Razor",
    rarity: "legendary",
    faction: "Wild card",
    type: "Investigative artifact",
    chase: true,
    copies: 1,
    text: "Occam’s, sharpened. The rest goes in the shredder.",
  },
  {
    id: 113,
    slug: "legally-mine",
    name: "Legally Mine",
    rarity: "legendary",
    faction: "Corporate",
    type: "Institution",
    chase: true,
    copies: 1,
    text: "The name does quite a lot of work.",
  },
  {
    id: 39,
    slug: "fathers-collection",
    name: "A Father’s Collection",
    rarity: "legendary",
    faction: "Franchisees",
    type: "Collection",
    chase: true,
    copies: 1,
    text: "Keep the memories. Find every piece.",
  },
  {
    id: 87,
    slug: "cecilia-romero",
    name: "Judge Cecilia M. Romero",
    rarity: "legendary",
    faction: "Wild card",
    type: "Judge",
    chase: true,
    copies: 1,
    text: "The calendar is now part of the strategy.",
  },
  {
    id: 2,
    slug: "franchisee",
    name: "The Franchisee",
    rarity: "common",
    faction: "Franchisees",
    type: "Character",
    chase: false,
    copies: 4,
    text: "Own boss. Allegedly.",
  },
  {
    id: 3,
    slug: "corporate-plant",
    name: "Corporate Plant",
    rarity: "common",
    faction: "Corporate",
    type: "Character",
    chase: false,
    copies: 3,
    text: "Just here to support the team. With a clipboard.",
  },
];

export const CATALOG_SIZE_HINT = 600;
