export const CATALOG = [
  {
    id: 200,
    slug: "legally-mime",
    name: "Legally Mime",
    rarity: "rare",
    faction: "Wild card",
    type: "Character",
    kind: "unit",
    chase: true,
    cost: 3,
    atk: 1,
    hp: 3,
    text: "His counsel is to remain silent. Instant: cancel a pending hostile tactic unless the Stage is already Court.",
  },
  {
    id: 31,
    slug: "bjc",
    name: "BJC",
    rarity: "rare",
    faction: "Wild card",
    type: "Character",
    kind: "unit",
    chase: true,
    cost: 4,
    atk: 2,
    hp: 3,
    text: "The stream has notes. On arrival: privately inspect the opponent’s oldest hand card.",
  },
  {
    id: 1,
    slug: "ammon-razor",
    name: "Ammon’s Razor",
    rarity: "legendary",
    faction: "Wild card",
    type: "Artifact",
    kind: "artifact",
    chase: true,
    cost: 5,
    atk: 0,
    hp: 0,
    text: "Occam’s, sharpened. At the start of your turn, pay 1 budget if able to retrieve your most recently discarded Protection card.",
  },
  {
    id: 113,
    slug: "legally-mine",
    name: "Legally Mine",
    rarity: "legendary",
    faction: "Corporate",
    type: "Institution",
    kind: "artifact",
    chase: true,
    cost: 6,
    atk: 0,
    hp: 0,
    text: "The name does quite a lot of work. Guard. Legal units you control get +1 health.",
  },
  {
    id: 39,
    slug: "fathers-collection",
    name: "A Father’s Collection",
    rarity: "legendary",
    faction: "Franchisees",
    type: "Collection",
    kind: "artifact",
    chase: true,
    cost: 4,
    atk: 0,
    hp: 0,
    text: "Keep the memories. Find every piece. After a fight, draft an extra card.",
  },
  {
    id: 87,
    slug: "cecilia-romero",
    name: "Judge Cecilia M. Romero",
    rarity: "legendary",
    faction: "Wild card",
    type: "Judge",
    kind: "unit",
    chase: true,
    cost: 5,
    atk: 2,
    hp: 5,
    text: "The calendar is now part of the strategy. Stage: Federal Court while she is in play.",
  },
  {
    id: 2,
    slug: "franchisee",
    name: "The Franchisee",
    rarity: "common",
    faction: "Franchisees",
    type: "Character",
    kind: "unit",
    chase: false,
    cost: 1,
    atk: 1,
    hp: 2,
    text: "Own boss. Allegedly. Starter copy — playable, not filed.",
  },
  {
    id: 3,
    slug: "corporate-plant",
    name: "Corporate Plant",
    rarity: "common",
    faction: "Corporate",
    type: "Character",
    kind: "unit",
    chase: false,
    cost: 2,
    atk: 1,
    hp: 2,
    text: "Just here to support the team. With a clipboard.",
  },
];

export const CATALOG_SIZE_HINT = 600;

export const byId = Object.fromEntries(CATALOG.map((c) => [c.id, c]));

export const RARITY_MARK = { common: "●", rare: "◆", legendary: "★" };
export const FINISH_LABEL = { standard: "Standard", foil: "Foil", holographic: "Holographic" };
